## Práctica 6
## Naive Bayes
## Vianey Maravilla Pérez

**Especificaciones:**

- Los dataset utilizados para esta práctica serán *iris.csv* y *emails.csv*:

**Dataset: Emails.csv***
- La primera columna indica el id del correo
- La última columna indica si el correo es spam o no
- El resto de las columnas son las palabras más comunes en todos los correos

**Dataset: Iris.csv**
- Las primeras 4 columnas son las características de las instancias
- La última columna es la clase

**Dataset: Ambos datasets**
- Carga el dataset
- Crea un conjunto de entrenamiento del 70% de las instancias y el conjunto de pruebas con el 30% (set random_state=0)


- Utilizando el conjunto de entrenamiento crea un conjunto de validación con 3 pliegues

**Utilizando el conjunto de validación realiza lo siguiente con cada pliegue:**
- Determina la exactitud de cada pliegue
- Determina el promedio de exactitud de los 3 pliegues

**Utilizando Multinomial con distribución normal para entrenar y prueba el modelo en cada pliegue:**
- Determina la exactitud de cada pliegue
- Determina el promedio de exactitud de los 3 pliegues

In [308]:
# Importamos las librerias que se requieren para la realización de la práctica

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold 

from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay



# EMAILS

In [309]:
# Importamos el csv de EMAILS y lo visualizamos 

emails = pd.read_csv(r"emails.csv", sep = ',', engine = 'python')
print (emails)

       Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff 

In [310]:
# Guardamos las variables X e Y con los siguientes valores

X = emails.drop(emails.columns[[0, len(emails.columns)-1]], axis = 1).values
y = emails['Prediction'].values

In [311]:
# Visualizamos lo siguiente con la variable de los nombres en X
nombresX = emails.columns[1:(len(emails.columns)-1)]
print(X.shape)
print(nombresX)

(5172, 3000)
Index(['the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou', 'in',
       ...
       'enhancements', 'connevey', 'jay', 'valued', 'lay', 'infrastructure',
       'military', 'allowing', 'ff', 'dry'],
      dtype='object', length=3000)


In [312]:
# Hacemos la división del conjunto de entrenamiento y de prueba con sus respectivos porcentajes

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, shuffle = True, 
                                                   random_state = 0)

# División de K pliegues

**Mediante clases se hara las divisiones correspondientes**

In [313]:
# Almacena una división extra de los respectivos datos de entrenamiento (validación)
class validation: # validación por KFold
    def __init__(self, X_train, y_train, X_test, y_test):
        self.X_train = X_train
        self.y_train = y_train
        self.X_test  = X_test
        self.y_test  = y_test

In [319]:
# Almacena los respetivos datos de prueba
class test:
    def __init__(self, X_test, y_test):
        self.X_test = X_test
        self.y_test = y_test

In [320]:
# Almacena todas los datos divididos de entrenamiento con su división
# Así mismo como los datos de prueba

class dataset_v:
    def __init__(self, validation, test):
        self.validation = validation
        self.test = test

In [321]:
# División de los datos con los pliegues

# Definimos el número de pliegues y su lista de almacenamiento de los pliegues
pliegues = 3
validations = []
kf = KFold(pliegues)

for train_index, test_index in kf.split(X_train):
    print("TRAIN:", train_index, "\n", "TEST:",
          test_index)  # imprime los indices del dataset original que fueron elegidos como X_train y ahora, que seran usados como conjunto de train y de test
    X_train_, X_test_ = X_train[train_index], X_train[test_index]
    y_train_, y_test_ = y_train[train_index], y_train[test_index]
    print(X_train_.shape)
    print(X_test_.shape)
    print(y_train_.shape)
    print(y_test_.shape)
    



TRAIN: [1207 1208 1209 ... 3617 3618 3619] 
 TEST: [   0    1    2 ... 1204 1205 1206]
(2413, 3000)
(1207, 3000)
(2413,)
(1207,)
TRAIN: [   0    1    2 ... 3617 3618 3619] 
 TEST: [1207 1208 1209 ... 2411 2412 2413]
(2413, 3000)
(1207, 3000)
(2413,)
(1207,)
TRAIN: [   0    1    2 ... 2411 2412 2413] 
 TEST: [2414 2415 2416 ... 3617 3618 3619]
(2414, 3000)
(1206, 3000)
(2414,)
(1206,)


In [322]:
# Cada pliegue se agregara a una lista de validacion
validations.append(validation(X_train_, y_train_, X_test_, y_test_))
# Almacenamos los conjuntos originales de prueba de los datos
tes_data = test(X_test, y_test)

# Almacenamos X en pliegues y el dataset del conjunto de pruebas
data_set = dataset_v(validations, tes_data)

In [323]:
# Multinomial - Gauss 

modelos = ['Gauss', 'Multinomial']
data_name =[]
clasif = []
promedios = []
exactitudesPrueba = []

# Gauss en 3 pliegues

In [324]:
npliegue = 0
exactitudes = []
data = 'emails.csv'
modelo = 'Gauss'
for pliegue in validations: 
    pliegues = pliegues+1
    clf = GaussianNB() 
    clf.fit(pliegue.X_train, pliegue.y_train) 
    predict_y = clf.predict(pliegue.X_test)
    names = clf.classes_
    print(names)
    # names = names.tolist()
    # Visualizaciones
    print ("____________________________________")
    print ('\tGaussian Naive Bayes')
    print(f'Pliegue: {n_pliegue}')
    print('Prediccion:', predict_y, ",", predict_y.shape)
    print ("____________________________________")
    print('Probabilidades sin función')
    print(f'Clases: {names}')
    print(clf.predict_proba(pliegue.X_test))
    exactitud = accuracy_score(pliegue.y_test, predict_y)
    exactitudes.append(exactitud)
    print ("____________________________________")
    print(f'Accuracy: {exactitud}')
    print(f'Instancias predichas correctamente: {accuracy_score(pliegue.y_test, predict_y, normalize=False)}') 
    print ("____________________________________")
    print('\nReporte de clasificación')
    print(classification_report(pliegue.y_test, predict_y))
    print ("____________________________________")
    print('\nMatriz de confusión')
    print(confusion_matrix(pliegue.y_test, predict_y, labels=clf.classes_))
    print ("____________________________________")
print(exactitudes)
print ("____________________________________")
promedioExac = sum (exactitudes) / len(exactitudes)
promedios.append(promedioExac)
data_name.append(data)
clasif.append(modelo)
print(f'Promedio de exactitud de la predicción en los pliegues:{promedioExac}')

[0 1]
____________________________________
	Gaussian Naive Bayes
Pliegue: 2
Prediccion: [0 0 1 ... 1 0 1] , (1206,)
____________________________________
Probabilidades sin función
Clases: [0 1]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]
____________________________________
Accuracy: 0.9494195688225538
Instancias predichas correctamente: 1145
____________________________________

Reporte de clasificación
              precision    recall  f1-score   support

           0       0.98      0.95      0.96       852
           1       0.89      0.94      0.92       354

    accuracy                           0.95      1206
   macro avg       0.93      0.95      0.94      1206
weighted avg       0.95      0.95      0.95      1206

____________________________________

Matriz de confusión
[[811  41]
 [ 20 334]]
____________________________________
[0.9494195688225538]
____________________________________
Promedio de exactitud de la predicción en los pliegues:0.9494195688225538

In [325]:
pliegues = 3
n_pliegue = 0
exactitudes = []
data = 'emails.csv'
modelo = 'Multinomial'
for pliegue in validations: 
    n_pliegue = n_pliegue+ 1
    clf = MultinomialNB() 
    clf.fit(pliegue.X_train, pliegue.y_train) 
    predict_y = clf.predict(pliegue.X_test)
    names = clf.classes_
    print(names)
    # names = names.tolist()
    # Visualizaciones
    print ("____________________________________")
    print ('\tMultinomial Naive Bayes')
    print(f'Pliegue: {n_pliegue}')
    print('Prediccion:', predict_y, ",", predict_y.shape)
    print ("____________________________________")
    print('Probabilidades sin función')
    print(f'Clases: {names}')
    print(clf.predict_proba(pliegue.X_test))
    exactitud = accuracy_score(pliegue.y_test, predict_y)
    exactitudes.append(exactitud)
    print ("____________________________________")
    print(f'Accuracy: {exactitud}')
    print(f'Instancias predichas correctamente: {accuracy_score(pliegue.y_test, predict_y, normalize=False)}') 
    print ("____________________________________")
    print('\nReporte de clasificación')
    print(classification_report(pliegue.y_test, predict_y))
    print ("____________________________________")
    print('\nMatriz de confusión')
    print(confusion_matrix(pliegue.y_test, predict_y, labels=clf.classes_))
    print ("____________________________________")
print(exactitudes)
print ("____________________________________")
promedioExac = sum (exactitudes) / len(exactitudes)
promedios.append(promedioExac)
data_name.append(data)
clasif.append(modelo)
print(f'Promedio de exactitud de la predicción en los pliegues:{promedioExac}')

[0 1]
____________________________________
	Multinomial Naive Bayes
Pliegue: 1
Prediccion: [0 0 1 ... 1 0 1] , (1206,)
____________________________________
Probabilidades sin función
Clases: [0 1]
[[1.00000000e+000 1.36147654e-029]
 [1.00000000e+000 2.01630547e-072]
 [2.47409574e-007 9.99999753e-001]
 ...
 [1.99238367e-186 1.00000000e+000]
 [1.00000000e+000 0.00000000e+000]
 [1.48863334e-048 1.00000000e+000]]
____________________________________
Accuracy: 0.9469320066334992
Instancias predichas correctamente: 1142
____________________________________

Reporte de clasificación
              precision    recall  f1-score   support

           0       0.97      0.95      0.96       852
           1       0.89      0.94      0.91       354

    accuracy                           0.95      1206
   macro avg       0.93      0.94      0.94      1206
weighted avg       0.95      0.95      0.95      1206

____________________________________

Matriz de confusión
[[810  42]
 [ 22 332]]
_________

In [270]:
# Modelamos ahora una tabla con los datos
datos ={'| Data Set |': data, '| Clasificador |': clasif , '| A.Prom |': promedios}

In [271]:
# Metemos el modelo dentro de un dataframe
tabla_modelo = pd.DataFrame(datos)

In [272]:
# Visualizamos
print(tabla_modelo)

  | Data Set | | Clasificador |  | A.Prom |
0   emails.csv            Gauss    0.949420
1   emails.csv      Multinomial    0.946932


# Multinomial en los conjuntos de entrenamiento

In [281]:
# Se aplica el modelo multinomial a los conjuntos de entrenamiento
for modelo in modelos:
    if modelo == 'Gauss':
        clf = GaussianNB()
        print('\t Gauss Naive Bayes')
    elif modelo == 'Multinomial':
        clf = MultinomialNB()
        print('\t Multinomial Naive Bayes')
    elif modelo == 'Bernoulli':
        clf = BernoulliNB()
        print('\t Bernoulli Naive Bayes')
    else:
        print('No hay ese modelo por el momento, intente nuevamente')
        break
    
    # Respectivas visualizaciones
    print(data)
    clf.fit(X_train, y_train)
    predict_y = clf.predict(X_train)
    names = clf.classes_
    print(names)
    print ("____________________________________")
    totalpredic = predict_y.shape[0]
    print ("Prediccion:",predict_y, "\nTotal de Predicciones:", totalpredic)
    print ("____________________________________")
    print("Probabilidades sin función:")
    print(f'Clases:{names}')
    print(clf.predict_proba(X_train))
    exactitud = accuracy_score(y_train, predict_y)
    exactitudes.append(exactitud)
    print ("____________________________________")
    print(f'Accuracy: {exactitud}')
    print(f'Instancias predichas correctamente: {accuracy_score(y_train, predict_y, normalize = False)} de {totalpredic}')
    print ("____________________________________")
    print('\n\t Reporte de clasificación')
    print(classification_report(y_train, predict_y))
    print('\n\t Matriz de Confusión')
    matrix = confusion_matrix(y_train, predict_y, labels = clf.classes_)
    print(matrix)
    print('\n')

	 Gauss Naive Bayes
emails.csv
[0 1]
____________________________________
Prediccion: [1 0 0 ... 1 0 1] 
Total de Predicciones: 3620
____________________________________
Probabilidades sin función:
Clases:[0 1]
[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]
____________________________________
Accuracy: 0.9676795580110498
Instancias predichas correctamente: 3503 de 3620
____________________________________

	 Reporte de clasificación
              precision    recall  f1-score   support

           0       1.00      0.96      0.98      2561
           1       0.90      1.00      0.95      1059

    accuracy                           0.97      3620
   macro avg       0.95      0.98      0.96      3620
weighted avg       0.97      0.97      0.97      3620


	 Matriz de Confusión
[[2447  114]
 [   3 1056]]


	 Multinomial Naive Bayes
emails.csv
[0 1]
____________________________________
Prediccion: [1 0 0 ... 1 0 1] 
Total de Predicciones: 3620
_______________________________

In [290]:
for modelo in modelos:
    if modelo == 'Gauss':
        clf = GaussianNB()
        print('\t Gauss Naive Bayes')
    elif modelo == 'Multinomial':
        clf = MultinomialNB()
        print('\t Multinomial Naive Bayes')
    elif modelo == 'Bernoulli':
        clf = BernoulliNB()
        print('\t Bernoulli Naive Bayes')
    else:
        print('No hay ese modelo por el momento, intente nuevamente')
        break

    # Respectivas visualizaciones
    clf.fit(X_train, y_train)
    predict_y = clf.predict(X_test)
    names = clf.classes_
    print(names)
    print ("____________________________________")
    totalpredic = predict_y.shape[0]
    print ("Prediccion:",predict_y, "\nTotal de Predicciones:", totalpredic)
    print ("____________________________________")
    print("Probabilidades sin función:")
    print(f'Clases:{names}')
    print(clf.predict_proba(X_test))
    exactitud = accuracy_score(y_test, predict_y)
    exactitudesPrueba.append(exactitud)
    print ("____________________________________")
    print(f'Accuracy: {exactitud}')
    print(f'Instancias predichas correctamente: {accuracy_score(y_test, predict_y, normalize = False)} de {totalpredic}')
    print ("____________________________________")
    print('\n\t Reporte de clasificación')
    print(classification_report(y_test, predict_y))
    print('\n\t Matriz de Confusión')
    print(confusion_matrix(y_test, predict_y, labels = clf.classes_))

	 Gauss Naive Bayes
[0 1]
____________________________________
Prediccion: [0 0 0 ... 0 1 0] 
Total de Predicciones: 1552
____________________________________
Probabilidades sin función:
Clases:[0 1]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [1. 0.]]
____________________________________
Accuracy: 0.9484536082474226
Instancias predichas correctamente: 1472 de 1552
____________________________________

	 Reporte de clasificación
              precision    recall  f1-score   support

           0       0.98      0.95      0.96      1111
           1       0.88      0.95      0.91       441

    accuracy                           0.95      1552
   macro avg       0.93      0.95      0.94      1552
weighted avg       0.95      0.95      0.95      1552


	 Matriz de Confusión
[[1054   57]
 [  23  418]]
	 Multinomial Naive Bayes
[0 1]
____________________________________
Prediccion: [0 0 0 ... 0 1 0] 
Total de Predicciones: 1552
____________________________________
Probabilidades sin

In [293]:
# Modelamos ahora una tabla con los datos
datos ={'| Data Set |': data, '| Clasificador |': clasif , '| A.Prom |': promedios, '| A. Prueba |': exactitudesPrueba}

In [294]:
# Metemos el modelo dentro de un dataframe
tabla_modelo = pd.DataFrame(datos)

In [295]:
# Visualizamos 
print(tabla_modelo)

  | Data Set | | Clasificador |  | A.Prom |  | A. Prueba |
0   emails.csv            Gauss     0.94942       0.948454
1   emails.csv            Gauss     0.94942       0.941366


# IRIS

In [329]:
# Importamos el csv de iris y lo visualizamos 
iris = pd.read_csv(r"iris.csv", sep = ',', engine = 'python')
print (iris)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [330]:
# Guardamos las variables X e Y con los siguientes valores

X = iris.drop(iris.columns[[0, len(iris.columns)-1]], axis = 1).values
y = iris['species'].values

In [331]:
# Hacemos la división del conjunto de entrenamiento y de prueba con sus respectivos porcentajes

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, shuffle = True, 
                                                   random_state = 0)

In [334]:
# División de los datos con los pliegues
n_pliegues = 3
# Almacenamiento de cada pliegue
validation_iris = []
k1f = KFold

for train_index, test_index in k1f.split(X_train):
    print("TRAIN:", train_index, "\n", "TEST:",
          test_index)  # imprime los indices del dataset original que fueron elegidos como X_train y ahora, que seran usados como conjunto de train y de test
    X_train_, X_test_ = X_train[train_index], X_train[test_index]
    y_train_, y_test_ = y_train[train_index], y_train[test_index]
    print(X_train_.shape)
    print(X_test_.shape)
    print(y_train_.shape)
    print(y_test_.shape)
    validation_iris.append(validation(X_train, y_train, X_test, y_test))


TypeError: split() missing 1 required positional argument: 'X'

In [328]:
n_pliegue = 0
exactitudes = []
data = 'iris.csv'
modelo = 'Gauss'
for pliegue in validation_iris: 
    n_pliegue = n_pliegue+1
    clf = GaussianNB() 
    clf.fit(pliegue.X_train, pliegue.y_train) 
    predict_y = clf.predict(pliegue.X_test)
    names = clf.classes_
    print(names)
    # names = names.tolist()
    # Visualizaciones
    print ("____________________________________")
    print ('\tGaussian Naive Bayes')
    print(f'Pliegue: {n_pliegue}')
    print('Prediccion:', predict_y, ",", predict_y.shape)
    print ("____________________________________")
    print('Probabilidades sin función')
    print(f'Clases: {names}')
    print(clf.predict_proba(pliegue.X_test))
    exactitud = accuracy_score(pliegue.y_test, predict_y)
    exactitudes.append(exactitud)
    print ("____________________________________")
    print(f'Accuracy: {exactitud}')
    print(f'Instancias predichas correctamente: {accuracy_score(pliegue.y_test, predict_y, normalize=False)}') 
    print ("____________________________________")
    print('\nReporte de clasificación')
    print(classification_report(pliegue.y_test, predict_y))
    print ("____________________________________")
    print('\nMatriz de confusión')
    print(confusion_matrix(pliegue.y_test, predict_y, labels=clf.classes_))
    print ("____________________________________")
print(exactitudes)
print ("____________________________________")
promedioExac = sum (exactitudes) / len(exactitudes)
promedios.append(promedioExac)
data_name.append(data)
clasif.append(modelo)
print(f'Promedio de exactitud de la predicción en los pliegues:{promedioExac}')

[]
____________________________________


ZeroDivisionError: division by zero